package tags

const (
	Air             string = "Air"
	Ground          string = "Ground"
	Sea             string = "Sea"
	Weapon          string = "Weapon"
	Sensor          string = "Sensor"
	Static          string = "Static"
	Heavy           string = "Heavy"
	Medium          string = "Medium"
	Light           string = "Light"
	Minor           string = "Minor"
	FixedWing       string = "FixedWing"
	Rotorcraft      string = "Rotorcraft"
	Armor           string = "Armor"
	AntiAircraft    string = "AntiAircraft"
	Vehicle         string = "Vehicle"
	Watercraft      string = "Watercraft"
	Human           string = "Human"
	Biologic        string = "Biologic"
	Missile         string = "Missile"
	Rocket          string = "Rocket"
	Bomb            string = "Bomb"
	Torpedo         string = "Torpedo"
	Projectile      string = "Projectile"
	Beam            string = "Beam"
	Decoy           string = "Decoy"
	Building        string = "Building"
	Bullseye        string = "Bullseye"
	Waypoint        string = "Waypoint"
	Tank            string = "Tank"
	Warship         string = "Warship"
	AircraftCarrier string = "AircraftCarrier"
	Submarine       string = "Submarine"
	Infantry        string = "Infantry"
	Parachutist     string = "Parachutist"
	Shell           string = "Shell"
	Bullet          string = "Bullet"
	Grenade         string = "Grenade"
	Flare           string = "Flare"
	Chaff           string = "Chaff"
	SmokeGrenade    string = "SmokeGrenade"
	Aerodrome       string = "Aerodrome"
	Container       string = "Container"
	Shrapnel        string = "Shrapnel"
	Explosion       string = "Explosion"
)
